import React from 'react';
import { Chapter } from "../components/Components";
import { Divider, Grid, Header, Image, List, Segment } from "semantic-ui-react";
import * as Media from "../media/seven/ChapterSevenMedia";

class ChapterSeven extends React.Component {
    render() {
        return (
            <Chapter content={<div>
                <Header as="h1">Chapter Seven</Header>
                <Image src={Media.img1} fluid rounded />
                <Segment vertical>
                    <Header as="h4" textAlign="center" color="grey">River Exe, just past Milton's Bridge.</Header>
                </Segment>                
                <Header className="centered" as="h3">June 2017.</Header>
                <p className="quote"> "The day is predicted when the last drop of fresh water will have been drained from this planet. The theories upon which so dry a conclusion need not be analysed here. In any case, however acute the general water shortage may become, Devon's supply should be among the last to fail since Dyfnaint, the land of deep, dark valleys, is also the source of many springs".</p>
                <p className="quote-credit">D. St Leger- Gordon. </p>
                <Header as="h1">Bridgetown.</Header>
                <p>For this, our fourth leg of the walk, Charles and I met at Exebridge and leaving Charles’ car in the public car park, we drove in my old banger back to the lay-by close to Bridgetown Cricket Club. At the end of the last walk, Charles had secreted the Exe Head stone into the side of the river bank just across the footbridge. Now, he sought to retrieve it and whilst he was searching, I chatted for a short while, with the Grounds man for the Cricket Club. He was in the process of gathering some items from the back of his car and followed by a delightful Jack Russell proudly bearing a rubber ball clamped in his jaws. As they crossed the footbridge in the direction of the cricket grounds, my attention turned back to Charles, who was having little luck finding the stone in the soft muddy enclaves. After having a look, myself and finding not even a hint of the look-alike stone, we decided to call off the search and continue with the walk. We made our way along the road in the direction of Exebridge. Luckily, the road was quiet and we didn’t have long before we found a crossing at <b>Milton’s Bridge</b> over the Exe. Turning into <b>Broford Wood</b> we picked up stretches of overgrown green lanes and open fields that took us through the wooden valleys and up to the footpath just below Broford Farm.</p>
                <Image src={Media.img2} fluid rounded />
                <Header as="h1">Chilly Bridge.</Header>
                <p>The path brought us down to <b>Chilly Bridge</b>. Like Silly Bridge, mentioned earlier, the name of the bridge was interesting. I did wonder if the name had anything to do with the close proximity of a spring (which often produces cold water) or perhaps the dense canopy of the tree cover darkening the river and shading the bridge to create a cooling effect. Jervoise (19) had nothing to say on the matter, beyond a short description of the appearance and structure. For all its out-of the way and diminutive appearance, the bridge has long served as a crossing for the ancient route between Brompton Regis and Dulverton. Its more ancient predecessor may have acted as a crossing point for the old Roman road which ran up to the quay at Minehead (33) indicating its long importance to the trade and industry of the area. The bridge now has been relegated to a minor route, but has a charm of a medieval look (although thought to be of 19c stock) and still bears witness to the builders who made this little stretch of the river, more navigable. At the same time, it’s close proximity to the major road, A396, meant that when a fallen tree blocked the road at the site of the bridge, it had the effect of closing the road between Bridgetown and Exebridge in February 2014. Today such incidences tend to be resolved fairly swiftly with the benefit of heavy-duty chainsaws and lifting equipment. Alternative routes can be planned and motorists advised of delays and detours. No such troubles afflicted us on this day. For us it was the simple matter of climbing over a nearby gate and walking through open fields until we reached <b>Higher Stockham Wood</b>.</p>
                <Image src={Media.img3} fluid rounded />
                <br />
                <p>As we walked through the woods, we came across a gate and seeing that it was locked, also discovered that it provided access to a large fenced off area. We had arrived at a large-scale pheasant coops fenced off to protect the stock from roving foxes. Hudson’s words came to mind "way cut off by huge thorny hedges and fences of barbed wire-man's devilish improvement on the bramble” (37). In fact, we came across a number of these enclosures and in doing so, attempted to navigate our slippery way around them, all too often brushing up against thick undergrowth. It wasn’t much fun either, especially as it held out no obvious prospect of there being a clear exit further on. We, nonetheless, persisted although did consider whether to try our luck down by the river itself. Hudson must have considered this on similar occasions: "The river -follower must force his way through these obstacles, in most cases greatly to the detriment of his clothes and temper or should they prove impassable, he must undress and go into the water” (37).</p>
                <p>If we hadn’t been trying to follow the river as much as possible, we might have done well to climb up to Stockman Hill and pick up the footpath to Court Down which offers on a clear day marvellous views across the Exe Valley and on the other side towards the Barle valley and Dulverton.</p>
                <Image src={Media.img4} fluid rounded />
                <Header as="h1">Barlynch Abbey.</Header>
                <p className="quote">“First, they would have seen all the monastic houses within their locality dissolved, their monks and nuns dispersed, their contents confiscated by the Crown and carried away in carts, and the buildings dismantled for their materials and left to decay. What was left became useful quarry for the new owner of the land, who also took over the rights of presentation to any benefices that the monastery had once held”.</p>
                <p className="quote-credit">Roy Strong. A little history of the English Country church (2007).</p>
                <p>Somewhere, beyond the trees on the opposite side of the river was <b>Barlynch Abbey</b>, or rather the ruin of a building and former estate of an Augustine community established in the 12c. The abbey reportedly never had more than nine canons and was smaller than some of the better-known Abbeys of Tintern and Fountains. Rather less of it survives too. The Abbey was dissolved at the time of the Reformation in 1537 and ransacked, the silver reputedly stolen and lost or buried somewhere between the abbey and the former routes used by the monks, as they passed Louisa Gate, Hartford and St James Church, Upton (41). As the abbey fell into decline, it was dismantled, with much of its stone and timber being recycled to build neighbouring properties, including the 16/17c Barlynch Farmhouse, which stands on the old site. I discovered that the farmhouse featured in a 1944 Ealing film Halfway House, standing in for the original location of a Welsh Country Inn. The film offers only a fleeting glance of the farmhouse and the valley and is where ten guests find themselves “a pause to stand in time…a few hours in which to change your minds and hearts”.</p>
                <p>No such sentiment attached itself to the fate of the former abbey. Little more than crumbling walls survive and these are listed as at risk to the forces of natural erosion, but at the nearby Parish churches of Brushford, Brompton Regis, Bampton and Dulverton are the repository of some of the glass windows, tiles. Bells, screens and seats. At St Mary Magdalene church in Winsford, the massive ash door with straps of ironwork is thought to come from Barlynch Abbey (41).</p>
                <Image src={Media.img5} fluid rounded />
                <Header as="h1">Baronsdown Estate.</Header>
                <p>In the wake of the abbey demise, emerged the <b>Baronsdown Estate</b> which comprised some eleven farms and had a substantial house built by the Joyce Family (1656). During the 19c, the estate passed to Stucley Lucas, a keen huntsman and last Master of The North Devon Staghounds (1825). It was his land was included in Hobson’s Hunting Atlas (1850) and provided much opportunity for the hunting of stags and foxes. It seems ironic that in the mid 1960’s, The League against Cruel Sports bought up the estate and currently runs it as a Nature Sanctuary. The former <b>Baronsdown House</b>, described as “a moderate sized mansion” (42) and listed with woodland walks, ornamental ponds, Italian gardens and three lodges in 1919, at the time of its sale, was finally demolished although some of by the old building survive. There is a legend that the cannons built a secret passageway all the way from Barlynch Abbey and up through Barlynch Woods, to where is not made clear. Where it began or ended no-one has been able to discover, but it remains one of those quirky remnants of folklore that add a little spice to life. Perhaps, I can insert a new tall-tale twist to the legend, by stating, that I found the tunnel a year later and discovered that it connected the former abbey with the derelict folly in Sturridge Wood. It wouldn’t be true, except that I did visit the folly on a drizzly November afternoon. My friend, Robert had joined me to explore the places of interest for the book and we had parked at the Louisa Gate lay-by.</p>
                <p>On one side of the road was opening to <b>Sturridge Wood</b>, which stands host to a diminutive folly, not altogether easy to spot amongst the trees. Built of local stone it has a single open doorway leading into a rounded roofless tower. On the other side of the road, stands the former lodge house and gate opening to the former Baronsdown House. A footpath leads on from the gate and skirts the fenced off wildlife sanctuary set up by <b>The League against cruel sports</b> and winds its way down towards the A369 at the bottom of the valley. There were a number of signs about stating the place was under surveillance and camera located around the state suggesting a cold war atmosphere between those for and against hunting in the area.</p>
                <Segment vertical>
                    <Grid divided="vertically">
                        <Grid.Row columns={3}>
                            <Grid.Column>
                                <Image src={Media.img6} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img7} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img8} fluid rounded />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
                <br />
                <p>We were just keen to see what were left of the former buildings and gardens on the estate. Our approach down the former drive to the house, took us past an impressive array of ornamental trees planted either side that clearly have thrived in this location. Mature larches, maple, beech and close to where the house had stood, a majestic cedar tree. In what I took to be the grounds of the former lawns, but now was rough grassland, trees had been planted. A closer inspection of the plaques commemorating each planting showed the names of supporters of the League. Some bore witness to prominent names, including Tony Benn (an Oak tree), Tony Banks (horse chestnut) and Eric Heffer (oak).</p>
                <p>A little further on, the ground began to slope down to the valley and older woodland reasserted itself. A number of small and large ornamental ponds were found along the former terraces, that threaded their way along the fringes of the upper slopes. In places, the terraces were cut into the sides of the hill and large stone wall acted as retainers holding back to steep sides. In places, small waterfalls trickled down the stone work, feeding a mass of mosses and discolouring the rocks and finding its way into the dark pools below. The pools were completely still, almost eerily so, its surface carpeted with autumnal coloured leaves, casting more shade upon the dark waters below. It reminded me of the magical effect of the painting “Dark Pool “by the Devon Painter, Judith Ackland (1992-1971). Winding our way around the upper slopes of the garden, the tree covers even in Winter casts a darkening effect on the uncultivated re-wilding impression. I tried to imagine these grounds in their former landscaping heyday. The aspect would have been kept more open to offer the fine vies across the valley and encourage the light and warmth into the former flower beds. Both would have been important to the former kitchen garden we came across, its glasshouses, now broken, derelict and in a state of ruin and decay. Former garden sheds still had some rotting tools of their former occupancy. There was a witness to the impermanent nature of things and the power of Nature slowly reasserting itself. I found the experience utterly absorbing. From a promontory, it was just about possible to look down the valley towards Barlynch Farm and site of the former abbey. The dense undergrowth and woodland offered at best a cluttered view, but there it was and beyond Helebridge Wood, where Charles and I had walked the year before.</p>
                <p>As Robert and I made our way back along the track overlooking <b>Little Baronsdown</b> (a modest but pleasant looking house, which looked unoccupied but presumably still in use) we saw the former stables which appeared to have been to the rear of the mansion and still retaining the cobbled courtyard. Every now and then, some of the safest pheasants in the land would present themselves either in flight or out feeding. The scene reminded me of the paintings by the late Gordon Beningfield, whose legacy was in co-founding The Countryside Restoration Trust, promoting sustainable agriculture alongside restoring wildlife habitats.</p>
                <Image src={Media.img9} fluid rounded />
                <Header as="h1">Helebridge.</Header>
                <p className="quote">“A short distance below the ruins (Barlynch Abbey) is Hele Bridge, by which the road to Dulverton crosses the river. It is a favourite trysting place with the Dulverton folk, and the view up the stream is very striking”.</p>
                <p className="quote-credit">Rambles in Somerset (1912).</p>
                <Image src={Media.img10} fluid rounded />
                <br />
                <p>Returning the year before and the walk, Charles and I, were engaged in. We remained on the other side of the river unable to see the former Augustinian Priory lying somewhere hidden amongst the dense growth of trees. The abundance of water fed by the numerous springs in the valley gave a wonderful sense of vibrancy and fertility. Emerging from Helebridge Wood we walked through open farmland until we arrived at <b>Helebridge</b>. The evidence that in days gone by this would have been an important crossing point is borne out by the substantial nature of the medieval bridge with its three-pointed arches and wider passage. The bridge serves as the link between the steep rise to Dulverton via Jury’s Hill and Machine Cross, the start of the ancient ridgeway towards Minehead. More importantly, it was (and perhaps, still is) a favoured courtship destination for the locals, although we saw no hank-panky going on. We stepped onto the bridge at one of those marvellous calm moments, when everything seems so quiet and undisturbed. I only realised that, later when a large bus and a camper van tried to negotiate the narrow bridge at the same time. The sight and sound of these two vehicles jolted us out of what had been a rather serene setting and in Charles’ case, an opportunity to check the map. We swiftly retreated from the middle of the bridge and walked in the direction of a highly desirable 17c/18c farmhouse which was clearly well-loved and maintained. Best of all, it had a fine position, overlooking the river.</p>
                <Image src={Media.img11} fluid rounded />
                <Segment vertical>
                    <Header as="h4" textAlign="center" color="grey">Meadowsweet on roadside verge.</Header>
                </Segment>
                <Header as="h1">Dulverton.</Header>
                <p className="quote">“Set in all the glory of the great amphitheatre Nature made, with the woods and hills of Exmoor closing round its three sides” .</p>
                <p className="quote-credit">Arthur Mee. The King’s England. (1940)</p>
                <Image src={Media.img12} fluid rounded />
                <br />
                <p>This very grand house stands close to the road to <b>Dulverton</b>, which climbs steeply from Hele Bridge. Dulverton just a few miles away. It wasn’t on our route, but a place, I have passed through over the years on my way up to Exmoor. I can think of only two fleeting occasions when spotting a rare parking space in Fore Street, the shopping heart of the village, I have spontaneously stopped to have a lightening inspection. Otherwise, my memory is of concentrating like mad trying to navigate through the narrow labyrinthine streets and negotiating traffic and pedestrians. On a subsequent return one fine November day, Kathy and I approached Dulverton along the narrow B3222 winding its way past a tight collection of houses closely hugging either side of the road. Below there was the view of <b>The River Barle</b> and the approach to Dulverton. It makes for a scenic entry into the town, but for my money, no better view could be found than from the heights of Burridge Wood with its ancient tracks or from Cottage Lane, which passes one of the exquisite hillside houses.</p>
                <Image src={Media.img13} fluid rounded />
                <p>From these vantage points you get a good sense of the amphitheatre effect with the steep wooded sides of Oldberry Castle, Pixton House and Court Down. The batches of mature tall larch trees which proliferate this area add a mountainous effect to the valley. Crossing the Barle, you enter the village and turning into the nearby car park, we were able to have a fine walkabout. The statue of Lorna Doone commemorating the legacy of R.D. Blackmore’s Exmoor book stands prominently at the approach to the town. The recent centennial Armistice was marked by a bouquet of poppies held in her left hand. The River Barle was in full flow from the recent rains, but nothing like the floodwaters surging through the valley on the 15th/16th August 1952, as I was to shortly discover.</p>
                <Image src={Media.img14} fluid rounded />
                <br />
                <p>As we turned into <b>Bridge Street</b>, I noticed an old wall, covered with the skeletal twine and seed pods of a climbing wisteria. At the centre of the wall was a plaque donated by two servicemen who were active in the management of the floodwaters around the bridge. The plaque indicated the height reached by the flood which went considerably over my head. I suspect, in his prime, Anthony would have just been able to keep his head above the water. However, as the owner of the wall and the house and the shop besides, he had only lived in the town since the early 1990’s. The shop is now up for let, but Anthony had previously run it as an Antique Shop, having relocated the business from the Cotswolds. Now fully retired and off to have his lunch at <b>The Bridge Inn</b>, conveniently just across the road, he spoke about how the Antique trade is as much about fashion as economics. The town certainly appears prosperous enough with nice shop displays and upmarket wares. Importantly, from our perspective, there were two charity shops and a particularly nice Bookshop, ‘Rothwell and Dunworth’, to grace our way around the town. The latter having all the ingredients of a bibliophile’s haven; well stocked and displayed books, chairs and even a sofa and plenty of light pouring through the windows overlooking the town. We had arrived in the town early and in time to witness the awakening of the town with its hustle and bustle. Standing at the top of the steps of the Town Hall, I shamelessly people watched, as drivers gingerly negotiated the narrow corridor of Fore Street with its parking spaces temporarily prime real estate. All the while, a hawkish traffic warden monitored the tickets. </p>
                <Segment vertical>
                    <Grid divided="vertically">
                        <Grid.Row columns={3}>
                            <Grid.Column>
                                <Image src={Media.img15} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img16} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img17} fluid rounded />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
                <br />
                <p>As the narrow pavements began to fill up with early morning shoppers, it was nice to reach the sanctuary of the lych-gate and churchyard of <b>All Saints Church</b>. A very friendly shaggy-looking dog bobbed up and down at the porch entrance taking its lead from its owner’s busy making the place look welcoming. I was on the search for the stained-glass window in the aisles donated by <b>Sir George Williams (1821-1905)</b> having found out a little more about this man. He was the youngest of eight sons, born to Amos and Elizabeth Williams at <b>Ashway Farm</b>. It is still there and if anything makes me want to follow The River Barle, then the setting for this farm on the edge of the moor and overlooking the river is very tempting. Looking at the map there are some lovely sounding names for the stretch of river along this part of the valley; <b>Cinder Pool</b> and <b>Three Waters</b>. The latter name denotes the three streams temporarily created, when the river meets a solid slice of higher ground, forming little islands. I haven’t been there (Yet!) but it’s one of the spots on the map that get the imagination and the desire to explore going.</p>
                <p>Williams, a self-described “careless, thoughtless, godless, sweary fellow” worked on the farm until he reached, the age of twenty. He first tried work in a Draper’s shop in Bridgewater and when this didn’t work out, he sought better luck in London. He found a job in a Draper’s shop, but having no-where to stay, slept in one of the store rooms with other similarly impoverished employees. Whatever, bad habits he may have had in Somerset, he was able to leave these behind.  The experience of trying to survive in the harsh circumstances he found in London as a young man spurred rather than defeated him. He sought to improve not only his own situation but that of other young men faced with similar difficulties. He worked hard and established himself not only within the drapery business but among his colleagues and other businesses. He also, in the nature of the times, found religion and became an active member within the congregational church (43).</p>
                <Segment vertical>
                    <Grid divided="vertically">
                        <Grid.Row columns={2}>
                            <Grid.Column>
                                <Image src={Media.img18} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img19} fluid rounded />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
                <br />
                <p>He set about galvanizing support for the founding of a hostel (1844), whereby young men could stay and be encouraged to study The Bible. From this humble start, The Young Men’s Christian Association, or YMCA, as it is widely known today, has gone onto provide important support and accommodation for young people (unisex now) across the world. A convert to his mission was his boss, George Hitchcock who helped with the funding and promoted George to management, a position, he carried on, as Son-in-law, when he married Helen Hitchcock. Knighted in 1894 by Queen Victoria in her Birthday Honours list and buried later at St Paul’s Cathedral in London. I couldn’t help wondering, if the present of the stained-glass window to All Saints was more than just a goodwill gift. It may well have been an act of atonement and I suspect a way of reminding people that he had amounted to something through his efforts and good deeds. </p>
                <Image src={Media.img20} fluid rounded />
                <br />
                <p>Leaving the church and the shaggy dog, we made our way down the Yew Avenue in the direction of Lady’s Street and in particular, the Bible Christian Chapel (1902) which stands just a little way down this narrow road. Now a private residence, it bears the memory of its membership in the stone memorials at the cornerstones. At one time, there was tension between efforts to establish a Methodist presence in the town alongside the older Congregational chapel. Mobs disrupted Methodist services held in a meeting room in the town but never completely subdued its calling and the former chapel, built in 1902, held up to 200 members of its congregation. Today, the older Congregational Chapel (1831) still continues. Returning the centre of the town, we found a nice tearoom and overheard a delightful opening line, “What shall we do with the rest of the day?” The talk soon moved onto talk about Brexit and the last snippet was about a couple who had booked tickets on a train but finding their seats taken had been unable to persuade the people occupying the seats to vacate. What seemed to redeem the story, was a man a few seats down, who volunteered to give up his seat instead. So, chivalry is not completely dead. </p>
                <Image src={Media.img21} fluid rounded />
                <Header as="h1">Pixton Park.</Header>
                <p className="quote">“The park at Pixton is of peculiar character. Wild, steep and undulating. To the left is a river bank, studded with beeches ad groves of fi. In the front, the ground falls into a romantic glen, the favourite herd of fallow deer which repairing in sheltered spot, show neat forked heads above the luxurious fern or graze in groups along the sunny glade”.</p>
                <p className="quote-credit">John Berhard Burke (1854) </p>
                <Image src={Media.img22} fluid rounded />
                <br />
                <p>From the centre of Dulverton, High Street runs into Jury’s Lane and just beyond <b>Jury’s Cross</b>, stands North Lodge, which opened the way to The Drive to <b>Pixton Park</b>. This sporting estate developed from more humble manorial beginnings at the time of The Norman Conquest. By the 1800’s, it was being developed by the Acland Family as a Deer Park with tree-planting and extensive landscaping. The house was greatly extended and refurbished, a process that continued with a succession of Earls of Carnarvon right up until the early 1970’s. It is reported that in 1910, the estate comprised some 4000 acres of wood and moorland. Hunting and entertaining were very much the hallmark of the lifestyle. Hounds were kept in kennels close to the North Lodge and used in Stag hunting and shooting pheasants (44).</p>
                <Image src={Media.img23} fluid rounded />
                <Segment vertical>
                    <Header as="h4" textAlign="center" color="grey">St. Nicholas Church, Brushford.</Header>
                </Segment>
                <br />
                <p>If you go back far enough, you come to George Herbert, 5th Earl of Carnarvon (1866-1923), the Egyptologist, who discovered the tomb of Tutankhamen. He sold the house and the estate to his Step- Mother, Elizabeth, Dowager Countess of Carnarvon, who in turn gave this to her eldest Son. In his short life, <b>Col. the Hon. Aubrey Nigel Henry Herbert (1880-1923)</b> packed an awful lot in. Diplomat, traveller, Intelligence Officer and Member of Parliament. Born into the wealthy landed family, he attended Eton and achieved a First-Class Degree in modern History at Oxford and travelled widely (sometimes dressed as a tramp) and developed a diplomatic reputation in the events surrounding the Balkan conflicts. Albania, on two occasions, offered him the throne of Albania and whilst interested, he declined on advice from a family friend, the Prime minister, Herbert Asquith and the Foreign Office.  Herbert was given Pixton Park with its house and 5,000 acres by his Mother along with a villa in the Gulf of Genoa but did not live long to enjoy these as he died at the age of forty-three from blood poisoning during a dental operation. His Widow, the Hon. Mary Gertrude Vesey, continued to live on the estate with their four children; one of whom, Laura Herbert married the novelist, Evelyn Waugh. Mary converted to Catholicism and made use of an old corrugated iron prefabricated hut, known as The Iron Room on the estate, to hold services once a month. Villagers were able to attend these services, led by resident Priests, who were able to stay in a cottage on the estate. Mary lived on the estate until 1952, when the ownership passed onto his only son, Auberon, who never married and died in 1974 and following his death, the estate was broken up and divided between his Nephews.</p>
                <Image src={Media.img24} fluid rounded />
                <Header as="h1">Brushford.</Header>
                <p>Col. the Hon. Aubrey Nigel Henry Herbert was buried at the neighbouring village of Brushford, in The Herbert Chapel of the local church of St Nicholas. It was a place I had long wanted to visit. Not least because I had read that his memorial was a stone effigy to Herbert in the chapel and above his head, a ceremonial sword secured against the wall. The stone cold to touch also reportedly gives a hollow sound and when I tried this, I half-expected someone to tap back. Fortunately no -one did, although perhaps, the sound of the Saturday afternoon organist practice drowned out the sound. As luck would have it, the afternoon sunshine just managed to pierce through the thick orange-red stained glass window, a geometry of which forms a cross and illuminates the gloomy chapel beyond. By contrast, the late afternoon sunshine filled the wide seep of the churchyard. I was delighted to find the venerable Oak tree, its hollowed out form capable of housing me and still in good health, judging by the gathering of leaves still clinging onto its branches. Brushford once served as the railway station to Dulverton and a connection between Taunton to Barnstaple and the former Exe Valley Railway. Remnants of the line still remain in the form of old bridges and the lie of land, but the station now demolished, is the site of a building suppliers. It stands at the fork in the road for the old road to Brushford and the Dulverton road. Brushford New Road, a little further on, is lined with the houses and access to new estates that largely make up the village, complete with what appeared to be a new community hall with someone carefully tending the flower beds. At the beginning of this road, we had stopped at an interesting bric-a-brac cabin, unfortunately closed at the time of my visit. A well-attired couple were also staring through the window surveying what was up for sale, so I didn’t feel so conspicuous doing the same. “We rang the number” said the lady “and a man answered it. We asked him how much he wanted for the milk churn and he said £65 which we thought was way too high. Anyhow, good luck”.</p>
                <Image src={Media.img25} fluid rounded />
                <Header as="h1">Combe House.</Header>
                <p className="quote">“A land of streams! Some, like a downward smoke, slow-dropping veils of thinnest lawn, did go”.</p>
                <p className="quote-credit">The Lotos-Eaters. Alfred Tennyson.</p>
                <Image src={Media.img26} fluid rounded />
                <br />
                <p>The afternoon was wearing on and there was one more place, I hoped to see. <b>Combe House</b>, which lies in steep valley sided glorious isolation in its very own wooded valley. Quite how, I had imagined that this house would have been accessible to me was swiftly disabused. As I drove up the small country lane towards <b>Nutsford Bridge</b> with Brockey River meandering on one side and the former railway line on the other, my spirits rose when I came to an open gate with a sign saying Combe. I had found my quarry. Noticing a dog walker nearby, I asked if he knew anything about the place. In short order, the message was clear. At best, we could see a side of the building from a footpath and only after a circuitous overland route and for the most part the house was screened by trees. I mentioned the report of a massive candlestick made from silver and lead from a mine was worked close to the house, but the man said he hadn’t heard of either. “I have heard about the connection to Sir Francis Drake, though”, a reference to this historic figure marrying into the Sydenham Family in the 16c and possibly the link between the discovery of two Armada medals found at the house many years ago. So, we contented ourselves with a stroll along this quiet lane, the late afternoon sunshine poring through gaps in the trees and the constant babble of the river interrupted at times, by pheasant shooting breaking out at intervals on the upper fields and woods around <b>Langaller Hill</b>. The house was at one time owned by The Sydenham Family, who held it until bankruptcy forced the sale in 1871. At the time, <b>George Francis Sydenham (1861-1924)</b> who was born in the house was ten-years-old and his Father, the incumbent at Brushford Church. George progressed in the manner of his commemorative plaque on the wall at All Saints in Dulverton, a church where he served as churchwarden for 28 years and a community where he was family doctor and surgeon.</p>
                <Image src={Media.img27} fluid rounded />
                <Header as="h1">Rook Wood.</Header>
                <p>A little further up <b>Jury Hill</b>, we found a path towards <b>Rook Wood</b>. I noticed waves of Meadow-Sweet or Queen of the Meadows adorning the hedge bank with its distinctive broad leaves and yellowish-white flowers. Taking a small plume of flower, I rubbed this between my hands and smelt its sweet scent. As far as meadows go, the next one, we arrived at, was anything but meadow sweet. The sight of a solitary bull amidst his domain of tall meadow land was intimidating. For once, I was in complete agreement with Charles, that caution was the better part of valour. The bull was aware of us but clearly had our measure and rightly judged that we had the full measure of him. This was his turf. We pondered what to do, all the while, noting that he was making no effort to move and seemed more interested in grazing. We decided not to turn back but manoeuvre around the edge of the field, keeping a respectful distance and a wary eye. It was slightly disconcerting to hear the clucking call of a pheasant in the background. It reminded me of the words about trespassing written by Hudson; “worst of all is the thought that he is a trespasser. The pheasants crow loudly lest he should forget it”. Keeping as much ground between us and the bull, I confess I have had lighter moments, keeping an eye to possible escape points, in a way a Fire Safety Lecturer would have been proud. In no time we made our last few strides towards the far side fence and our guard dropped like an unseen weight. By now a fine misty rain was falling and I turned around to survey the bull in his pastoral empire. He had not moved one pace, presenting almost a harmless image of this awesome animal quietly and harmlessly engaged in munching grass.</p>
                <Image src={Media.img28} fluid rounded />
                <Segment vertical>
                    <Header as="h4" textAlign="center" color="grey">Wear Bridge.</Header>
                </Segment>
                <Header as="h1">Pixton Hill.</Header>
                <p className="quote">“And the wind went sighing over the land, tossing the grasses to and fro. And a rainbow held out its shining hand- so what could I do but laugh and go”</p>
                <p className="quote-credit">Bernard LaGallienne</p>
                <p>On reaching <b>Wear Bridge</b> we discovered the finely restored former sawmill, now serving as a well-to-do home and close by to a rustically weathered bridge. A similarly weathered picnic table and bench stood beneath the bridge offering a wonderful shaded sitting spot. In its former life as a sawmill for the surrounding forestry estates, the timber was cut by saws powered by a large waterwheel and later turbine. Slader (33) wrote that wooden keys for railways were made at the mills, but by the 1960’s, the work had scaled down and at the time of his writing (1960’s) it was producing kitchen furniture. The turbine engines introduced in 1939 replacing the water driven wheel would not have been affected by the water levels. If they were still in use, the recent dry weather and marked reduction in the water levels, was a reminder of the importance of water as a source of energy and not something to take for granted. Below the bridge was sight of the exposed rocky platform that normally would be covered with flowing water. However, the same weather conditions had not curbed the thick cover of brambles and stinging nettles that carpeted just about every point along the river bank. This meant we could not follow the river by the most direct route.</p>
                <Segment vertical>
                    <Grid divided="vertically">
                        <Grid.Row columns={3}>
                            <Grid.Column>
                                <Image src={Media.img29} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img30} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img31} fluid rounded />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
                <br />
                <p>So, we ascended the track up Pixton Hill cloaked in tall majestic larch making up the very pleasingly named <b>Puzzlecombe Copse</b>.  It was on the foothold of this hill that we came across a semi derelict house with gabled windows and surrounding wildly overgrown gardens. It was just the kind of hidden treasure I love to discover and inevitably sought to get as close as I dared to get a good view. Some of the windows were boarded up but it was just about possible to get a peek inside some of the empty rooms that showed some evidence of an attempt at restoration. On the front door was a letter box with a bat figure and in keeping with this Chiropterophilia (fancy name for love of bats) was a bat box to the side of the house. This place we decided would have made a lovely retreat and this was only reinforced as we continued to ascend the hill and finding an enjoyable pathway through the woods and stepping out of this on the grassland ridge that rounded the top of <b>Pixton Hill</b> the views were impressive. I still remember to this day, an image conjured up by a book, I’ve enjoyed recently, giving a lovely description of the “softer, kinder valley” below. It makes me wonder, if he similarly sat on the hill, surrounded by the meadow grasses and on a sunny day. ‘More Devon Byways’, by Annan Dickson (1952) would prove a nice accompaniment to any travel offering “samples of little-known ways of discovering Devon’s three attractions- country, moors and sea”. I would definitely add, rivers to this list, particularly following a swimmer’s instinct for a good bathing spot. It was Charles, who had spotted the site of the Meeting of the Water on the map and out there in the distance, it lay. Annan Dickson wrote a tantalising description of the valley, that if I had known about it at the time, would have got my wild swimming enthusiasm racing. “Below, the fields show rich yellow pasture and lower down still stretch the green, level meadows where the Exe comes winding down to the point that the map marks just with the words “Pool”. The pool where two rivers join is usually a choice spot for anglers and for connoisseurs of river beauty. Here, it is especially so, there the Exe is joined by the Barle-big enough in its strength and volume of water, to push the channel well over to the valley side close under the main road northward- a lovely curving sweep of the river where oak and sycamore hang down from the steep bank”. As it was, the combination of the hot weather and prospect of a swim was all we needed to look forward to the next stage of the walk. However, before I take you down to the river, can I depart once again, to another time and visit, drawing from the other landmarks seen from this splendid promontory.</p>
                <Image src={Media.img32} fluid rounded />
                <br />
                <Image src={Media.img33} fluid rounded />
                <br />
                <p>With the aid of a map we could pick out any number of landmarks and not least the site of Bury Castle (hidden by trees) standing atop a bluff overlooking Weir Bridge below. It is just down from there that <b>The River Haddeo</b> makes its entry into the Exe, adding yet more momentum to its course. The River Haddeo, has its source just a few miles up from Upton, but is checked at the dam of Wimball Reservoir (opened in 1979). The water is released into the Haddeo just above the hamlet of Hartford and flows down the thickly wooded Hartford Bottom towards Bury and onto its meeting place with the Exe below Weir House and Bridge.</p>
                <p>All this put me in mind of Bun Burrows Walk and the January 2016 Radio Four edition “On your farm” with Ruth Sanderson entitled “Life in trees”. The story of Bun Burrows and his lifetime in Forestry. Standing in the ancient semi-natural Haddeo woodland, the interview was conducted with the accompaniment of rain falling in the background served to emphasise the outdoor nature of this former workplace. His partnership with Bernard Dru had begun in the mid 1970’s, when Dru had inherited Bury Estate and over a forty-year period, Bun worked prodigiously and rewardingly improving the woodland to its current state of healthy management. At the beginning of his stewardship, the woodland had been covered by a rhododendron infestation which was choking the life and diversity out of the woodland floor. Bun not only cleared this, but went onto plant some 200,000 trees by the time he retired just a few years ago at the tender age of 78 years. In honour of this achievement he was awarded a Long Service Medal by The Royal Forestry Society in 2008.</p>
                <p>Encouragingly the planting of trees also had a weighting towards hardwood trees, primarily Oak which continues to be the choice of timber used for Dru’s bespoke flooring and timber business. There is a close association with the Exmoor National Park recognising the importance of the woodland both as an industry and a part of the landscape. In his eighties, Burrows spoke of enjoying making trips from his nearby village of Oakford to keep an eye on the health of the trees. He rightly drew pride in his considerable handiwork and legacy for the future. It therefore, seemed entirely fitting that Bernard Dru had named a woodland walk in honour of his friend and former employee. The Bun Burrows Walk. Standing on the footpath that now bears his name, the route passes through the woodland he spent years planting and in spring, his favourite season. Bernard Dru considered the words chosen by the son of Sir Christopher Wren to mark his Father’s memorial at St Paul’s Cathedral in London; “Reader. If you seek monuments look around you”. Very apt.</p>
                <Header as="h1">Bun Burrows.</Header>
                <Image src={Media.img34} fluid rounded />
                <br />
                <p>I had the greatest of pleasures to meet Bun and his Wife, Brenda at their cottage, which lies near the top of the village. Turning up unannounced, Bun and Brenda adapted themselves very warmly and hospitably to our attention. Over a nice steaming cup of tea and plate of digestives, I sought to find out a little more about this personal hero of mine. He didn’t disappoint one tiny bit. He and Brenda are kindly decent country people who continue to play an active part in the community. The son of a farm labourer, (Upcott Farm) Bun had grown up in a tied cottage in Oakford, the village where he has lived all his 83 years. He attended school in Bampton, waiting at The War Memorial Cross for the bus to arrive, although on some days, he and a few school friends, would hide behind the memorial for the bus to pass and then walk the three-miles to school. The teacher, unaware of their jape, commended for walking. Bun had acquired the nickname “Bun” from his classmates and couldn’t recall why. It didn’t matter. He quite liked it. Brenda, also had grown up in the village, on Manor Farm, situated just across the road from where Bun and Brenda live now. They married at St Peters and went onto have two daughters, one whom we met briefly. Rather nicely, she described her Father as a hero of hers too! Bun worked as a farm labourer for a time, before taking up the suggestion of his friend, Stan, to work in forestry. Over the years, Bun worked over a number of private estates (e.g. Rackenford Manor) and for the Forestry Commission, planting (November), weeding and thinning (June and August) and cutting. His jobbing career in forestry took him to Dartmoor forests, the coast at Seaton and the golf course at Honiton. He and Stan found some amusement with a golf club they found. As they made their way around the green, they used the club to surreptiously knock on balls in play, so that when golfers turned up to where they though their ball had landed, they discovered it somewhere else. At the time, Bun and Stan were planting 1500 trees in a day. Most of the trees planted were softwood and larch rather than hardwoods, although, when Bun began to work for Dru, he got to plant more oak and beech interspersed with cash crops. Cutting had originally been done by hand held saws, but at the time, Bun was taking up forestry, chain saws were being introduced, although they were precarious to use in the early days. </p>
                <Image src={Media.img35} fluid rounded />
                <br />
                <p>Over the years, Bun had developed an extensive knowledge of trees and the value of their timber. He spoke about trees in a work-like manner rather than romanticised, as someone steeped in the commercial crop of timber. In some ways, Bun was a salutary reminder, how our evocation and celebration of the countryside often overlooks the working nature of the land. Nonetheless, there was richness in Bun’s knowledge of the shape and texture of both living trees in the woodlands and cut timber. He spoke about “Cats paws”, a highly desirable feature in wooden flooring and furniture, where the neck of a twig or small branch is sliced leaving its mark in the timber. A “Shaken tree” by comparison is an unwelcome sight with its shape contorted by a ruinous build-up of water trapped in its branches or trunk. This eye for the use of a tree came in handy when the owners of Warwick Castle wanted to restore an old oak table and Bun was able to select an oak tree from the estate that would serve admirably to make up the table legs. This eye for seeing the potential in a tree for a unique piece of furniture is something, I greatly admire. It was entirely fitting that just before we left the house to walk over to the church, Bun showed us a framed photo of his opening Bunny’s Walk in September 2017 with Brenda in attendance and Bernard Dru. Bun has followed in the tradition of bell-ringing (like his Father) and whilst Brenda was busy cleaning the church, he showed me around the bell tower and the plaque that commemorating his captaincy of the team. In retirement he had driven the community bus. We left Brenda busy pushing around a hoover in anticipation of the following morning’s service (“ten, if we’re lucky”) and the Armistice commemoration decorations she and other volunteers had so attentively displayed around the church.</p>
                <Header as="h1">Bury and the River Haddeo</Header>
                <Image src={Media.img36} fluid rounded />
                <p>As a little aside to this, I took a day out to visit <b>Bury</b> and explore the <b>Haddeo Valley</b>. I recommend you do this as well. It is a magical place. My walk through this handsome little hamlet, took me towards the ford and the narrow medieval bridge that spans the River Haddeo. On crossing the bridge, you are greeted with a number of fine-looking cottages and houses, all of which have distinctive ornamental character. The one that caught my eye, was the former chapel of ease, built in 1890, a year commemorated on the bell turret. It was formerly, the site of a school, built (1850) and supported by Lady Carnarvon of Pixton House. It was her Grandmother, <b>Lady Harriet Acland (1750-1815)</b> who had Lady Harriet’s Drive built during her long widowhood and it remains there to the present day. The drive runs alongside the River Haddeo and was built to connect Pixton Park, where her Daughter lived, to Harriet’s estate near Wiveliscombe. At Upton Village, there is a fine gate lodge, known as Pepperpot Castle stands. Harriet has a portrait at Killerton House, north of Exeter, where the Acland Family had a substantial estate. She made quite a reputation for herself during The American War of Independence. Her Husband, Major John Dyke Acland, was despatched to the former colonies, to take command of the 20th Regiment of Foot. Harriet went along too, taking with her staff, pets and her Mother! She kept a journal of her time there, including the account of learning that her Husband had been wounded and captured during The Battle of Saratoga 1777.</p>
                <Image src={Media.img37} fluid rounded />
                <br />
                <p>Despite her pregnancy, she endeavoured to come to his succour. Together, with a chaplain, maid and her Husbands’ valet, they rowed across The Hudson River at night. She made a representation to General Gates, commanding the Americas army, to be allowed to care for him. Impressed by her bravery, General Gates agreed and for several months, Harriet took care of her gravely ill Husband. In January 1778, she was allowed to return to England with her Husband and whilst on the return voyage, gave birth to their son, John. Tragically, Harriet was to lose her Husband, later in the year. Having fought a duel with a fellow officer over a snide comment about the Americans (whom he had cause to respect for their gentle treatment whilst in captivity), he caught a cold and died. She also lost her Son, John, at the age of 7 years, but had a surviving Daughter, Elizabeth, who went onto marry the 2nd Earl of Carnarvon and as part of her marital settlement received Pixton Park, which now came into The Herbert Family. So, the drive was a measure of the importance, Harriet placed on having contact with her soul surviving Daughter.</p>
                <p>The drive appears to have been cut out of the side of steep wooded banks and took me past several little cottages nestling close to the river. I passed a fishery, with a succession of water fed tanks that occasionally spluttered into life with the sound of splashing and water rippling. Otherwise, I felt completely alone in the stillness of the woodland and it was only when I passed a particularly attractive cottage as I made my way into the little hamlet of Hartford that I was jolted out of this semi-somnambulist state.  The layout of a few houses and the direction of the yellow arrows slightly threw me when working out where the next bit of the footpath was supposed to be. The yellow arrow seemed to be pointing in the direction of a drive with a garage at the end and the actual path was partially hidden by an overhanging climbing plant. Whilst I was pondering all this, a friendly couple in a nearby garden spied me and after a little explanation kindly directed me to carry on past this distinctly less travelled path, towards a much-waterlogged path stretch and just beyond this a welcome crossing by a ford bridge. </p>
                <Image src={Media.img38} fluid rounded />
                <Header as="h1">Wimball Reservoir.</Header>
                <p className="quote">“If I glance up when I’m walking there’s Thornworthy Tor overseeing the dam, making sure everything’s in order”.</p>
                <p className="quote-credit">Quote from Sidney Potter, former resident Warden at Fernworthy Reservoir. Taken from “My Dartmoor. Clive Gunnell. (1977).</p>
                <p>I continued along the path, which on rounding the bend in the valley, began to rise and it wasn't long before I became aware of a growing cacophony of water ahead. I noticed just above the tree canopy, the shape and form of the upper ramparts of the towering dam of <b>Wimball Reservoir</b>. A fork in the path either led up towards the walk along Haddon Hill and Deer Park or dropped down to the base of the dam and this was the route I took. Here the atmosphere changed to a sense of mild trepidation as the raw power of the water became much more evident. A continuous plume of water forced by the enormous pressure of the 21,000 mega litres trapped within the reservoir, surged out in a wide roaring uniform spray. Gradually, the spray began to arch into a white watery film hitting the surface of the frothing black water below. In doing so the water was fed into a series of large open water beds designed to harness the outflow. The effect of this collision of water was to create a fine mist that lingered heavily in the air. Staring over the barrier to the water chambers below, I did wonder at the prospect of swimming there but decided against this. There was something beguiling and menacing in the look of the water, something I have not experienced with a reservoir, firmly rooted in my childhood memories.</p>
                <p>If I go back far enough in time, I can remember summer camps up at <b>Fernworthy Reservoir</b> on Dartmoor. I must have been a Chorister at Exeter Cathedral at the time. Our family were guests of Mr and Mrs Potter and their son, Andrew. Through long association that went back to the early 1950’s, when my Mother and Grandmother were taken in by the kindly couple, following a flash flood that ruined a camping holiday nearby. During the times, we camped there, we were able to explore the area around the reservoir and if ever a setting could inspire stories and adventures this was it. A former quarry, where the stone for the dam was cut and fashioned and bits of rusting machinery lay abandoned became swampy woodland with Alder and Sallow. This little enclave became The Lost World, full of dinosaurs and secret hide-away. The real prizes were the little pools that formed along the rivulet of The South Teign that began just past the breakwater chambers at the base of the dam. These large chambers were strictly out of bounds for us to swim in, but always visible against the steep rise of the dam wall.  The wooden bridge that crossed over the fledgling river is still there and looks down on the same large rock pool, we children, just managed to splash about in on those hot summer days. I also recall gingerly walking along some of the storied ramparts of the granite wall to gaze down at the water chambers below. No such thought or possibility lay before me at Wimball. Standing behind a vast concrete wall rising some 160 feet and spanning a whole valley, the structure had an overwhelming effect. The tall vertical buttresses made up of stone quarried from Bampton has stood resolute since 1979 and supported a wall holding back 21,000 mega litres of water. D. St. Leger-Gordon wrote; “a river once dammed, with its flow regulated, like a bird which has been ringed or a branded animal, is inevitably deprived of its entirely natural or wild character, since neither the river nor animal is any longer quite as Nature made it” (10). To get a real sense of this, you really have to stand at the top of the dam and survey the open expanse of water held back by the wall. I began to ascend the concrete steps that followed close to the dam wall up to the South side of the valley. As I climbed the steps (losing my count as I progressed) I stopped at intervals, to gain a view of each section of the buttresses, poised in a wedge-shaped formation. Each acted like series of separate mini worlds, some with layered concrete walls towards one-another or in an irregular manner. This added a strong image textured by the range of colours fashioned by years of chemical reactions and exposure to the elements. For the most part, the wall was starkly beautiful, but devoid of any noticeable life. Only at the very base of each section of the wall, was the bare dry ground planted with the hardiest of vegetation.</p>
                <p>As I reached the top of the hill and the dam, I became very quickly aware that an event was going on here. The Iron Man Challenge 2017 was taking place and for the final time, it seemed. I came across the last of the competitors running along the dam walkway. Having crossed, they then, turned around and passed a row of tables that plastic cups from which the runners were offered water. I didn't know who I admired more: the runners of all sexes, ages and expressions, or the marshals assembled and supporting the runners with infectious enthusiasm. Either way, this appeared to be the final lap for the runners. Part of the challenge included a 1.9km swim in the reservoir which put me in mind of my own wild swim here in the summer of 2016. Kathy and I made a trip to the reservoir, whilst completing a pleasant tour of what is called The Coleridge Walk from Nether Stowey to Porlock.</p>
                <Header as="h1">Pixies Parlour. Ottery St Mary.</Header>
                <p>The walk is a celebration of <b>Samuel Taylor Coleridge (1772-1834)</b> a highly regarded Romantic Poet. Amongst his best-known poems is a personal favourite; “A frost at midnight” with the lines "or whether the secret ministry of cold shall hang them up in silent icicles quietly shining to the moon".</p>
                <p>Coleridge is linked with the heritage of the East Devon town of Ottery St Mary. Here he was born and his Father, the vicar of the splendid St Mary the Virgin, which stands prominently in the middle of the town. It seems Coleridge (Junior) had quite a troubled childhood and found escape along the banks of The River Otter. At the tender age of seven, he hid in a cave all night following an argument with a brother. The cave is still there and known as Pixies Parlour and is situated on the riverbank sandstone cliff overlooking The River Otter. Legend has it, that the Pixies had long regarded the valley and the river as their domain. However, as human settlement sprang up, they felt compelled to inhabit the margins of the valley and found refuge along the riverbanks. This is how the caves became known as The Pixies Parlour.</p>
                <Image src={Media.img39} fluid rounded />
                <Segment vertical>
                    <Header as="h4" textAlign="center" color="grey">River Otter.</Header>
                </Segment>
                <br />
                <p>The building of St Mary's the Virgin in the late 1340's was bad enough (Pixies being devout Pagans, of course) but the installation of the church bells gave vent to their worst fears. Fearing that each peal of the bells resulted in the loss of a Pixie, in 1454, they rose up in revolt, taking the bell-ringers captive and imprisoning them in Pixies Parlour. The bell-ringers were eventually able to make good their escape, but for the pixies, it was back to their confinement along the riverbanks. The only pixies you see today, bear an uncanny resemblance to local school children. Once a year, on a June evening, they emerge from Tip Hill, screaming and shouting uproariously. If that doesn’t seem enough to exact revenge, then it isn’t helped by villagers coming out to watch and egg them on. Any further art of surprise is then lost when the Pixies, then gather in The Square in all their dazzling finery. Surrounded by amused villagers, the chief pixie loudly announces the plan to abduct the bell-ringers from the church. Despite this breach in security, no-one appears to tell the vicar and the bell-ringers, who a few minutes later are brought down to The Square and imprisoned in a mock up entrance for a cave. Now I've read that if pixies hear 'bless my soul', they disappear, but with all the noise and bustle, it's doubtful anyone could have been heard yelling anything. Luckily, for the Bell-ringers, they got their hands on some hand bells, which set the entire troop of pixies heading off in the direction of Tip Hill and in the opposite direction of Pixies Parlour. Gradually a sense of calm descended over the square.</p>
                <p>Watching the spectacle was great fun and it was nice to see how a tradition like this (not forgetting the town's Tar Barrel Race in November) has endured for many years. No doubt Coleridge was familiar with the legend. In 1793, he escorted a party of women to the site, giving rise to his poem 'Songs of the Pixies' and the place where his Fairy Queen was anointed. Having visited the site, I was a little disappointed to see the cave has been fenced off, although, I imagine with good reason. Just through the fence I could catch a glimpse of the inscriptions made over the centuries judging by one of the lines from his poem; “as round our sandy grot appear many a rudely sculptur'd name".</p>
                <p>I do not know, if Coleridge might have taken part in the pageant or for that matter swum in The River Otter or any of the streams or rivers in The Quantocks. However, that is precisely what I did on that lovely autumnal afternoon in 2016 at Wimball Reservoir. I took an illicit dip in as discrete setting as I could find, first walking down some steps that led into the murky water. When the water reached my waist, I took a deep breath and dived into the water. It was slithery and still and as I swam into the depth, I could feel the enveloping coolness gathering all around me. This became my own secret ministry of cold. Rising to the surface and taking measured strokes, I began to swim unhurriedly towards the middle of the reservoir. At intervals, I would turn my head around to scan for any signs of unwanted detection, but the Gods of Wild Swimming seemed to be with me at least to the half-way point. Then, I caught sight of a boat someway off, but steadily closing the distance and decided a retreat was the best course of action. The memory of this swim was in my mind as I took the footpath leading up towards Deer Park with the view of the reservoir taking on its full shape.</p>
                <Image src={Media.img40} fluid rounded />
                <Header as="h1">Haddon Hill.</Header>
                <p className="quote">“Holloway- A hollow way, a sunken path. A route that centuries of foot-fall, hoof -hit, wheel-roll and rain-run have harrowed deep down into bedrock”. </p>
                <p className="quote-credit">Holloway. Robert Macfarlane, Stanley Donwood &mp; Dan Richards (2012)</p>
                <p>The highest point of <b>Haddon Hill</b> is marked by a trigonometry marker. The wind had got up a little and I pressed myself up on the southerly side, so that I could enjoy the views and have a little snack. Below, was Hadborough Plantation and leading out of this larch crop was <b>Haddon Lane Track</b>. This is where I found one of those unexpected joys of the day. The track was entirely downhill, a decided bonus and took me through one of those very old lanes that folds around you with its arching gnarled tree limbs and high mud banked sides. The landscape of the foothold, where each step commands your full attention. In wet weather, such lanes are slippery and loose stones can throw the foot or unsettle the pace. You navigate the mud for foothold places where you suppose, often wrongly, are less slippery. In heavy rain, small rivulets follow the edges of the sides or congregate in large puddles, making for a wet passage. In summer, the dense canopy casts a dark gloom in pockets making visibility difficult. In less travelled lanes, dense vegetation can create many obstacles in your path. It is in winter, when the hedges are stripped bare, that you can find the old layering of the Hedgeman’s handiwork. The arching thickened strips now bound and fused with the deeper recesses of the hedge. It harks back to a tradition of hedge laying, far less commonly observed today. The three main tools of the hedge-layer still remain in its practice. The rake to pull out the undergrowth, the billhook to cut the thorns and split the stem and the mallet to hammer in the poles around which the hedge was shaped. The gaps, in former times, would be filled with woven edders of hazel along the top to keep all the branches in place. I delight in the calendar of plant life found in these places, marking not only the seasons, but also the mood of the hedges expressed in renewal and decay. Each season, has its guests, colours and sound. I stop to take a close up view of a section of hedge, witnessing in minute detail these mini landscapes and roving insects at work. Haddon Lane Track continued for a long old time, taking me past some old barns and a farmhouse and a reminder to how ancient the land is. In Saxon times such lanes may have served as boundary lines denoting ownership of individual estates. And overlooking, the hamlet of Bury, to where I returned now, was the rising hill upon which the Bronze or Iron Hill fort still stands.</p>
                <Image src={Media.img41} fluid rounded />
                <Header as="h1">Meeting of the Waters.</Header>
                <p className="quote">“From Tarr, through woods and beauties all the way, the Barle runs down from Dulverton, and from the heights above this uninteresting little town you may take full gaze of the Barle, the Exe, and the Haddeo valleys, and be hard put to it to decide which is the loveliest”.</p>
                <p className="quote-credit">Ruth Manning-Sanders. The West of England (1949)</p>
                <Image src={Media.img42} fluid rounded />
                <br />
                <p>I return, once more to Pixton Hill and the scene, as I recall, of Charles and I, enjoying some lunch and looking down from this vantage spot, to the watery monument of the wonderfully named <b>Meeting of the Waters</b>. So- called because it marks the point where The River Barle meets with The River Exe and just below that is the equally evocative named Black Pool. To get there involved a delightful descent down Pixton Hill. Trailing through the grassland reminded me of the words and pictures, I used to delight in reading to my children, from The Bear Hunt book by Michael Rosen and Helen Oxenbury (1989). We navigated <b>Perry Farm</b> without getting shouted at and walked in the direction of the bridge near to the southerly tip of Puzzlecombe Copse. On the other side of the river, was the interestingly named <b>Snapbox Wood</b>, perhaps a reference to trapping of poachers or animals or both. From here we were able to follow the riverbank with a marvellous view of three commanding hills: Pixton Hill, Hulverton Hill and Whitstone Down. Reaching the point where the two rivers meet, Charles and I were determined upon a swim and the markers for the NUTS analysis were very favourable. The weather was hot and the cooling water below looked very enticing. Gaining access into the water proved a little tricky and required the constant testing of feet on the slippery stones that lined the river beds. This made entering into the water anything but regal and more like an awkward balancing act with long delays between each tentative step. In the end I chose a favoured technique for these situations. Quickest in and quickest dealt. If I couldn't dive, then at least I could sit down and manoeuvre myself towards the deepest pools that Charles had already found. In little time, I was able to launch myself forwards, sliding under the watery murky world in front of me.</p>
                <p>Holding my breath and opening my eyes, I felt like a visitor trying to make the most of my precious time in this underwater kingdom. Even though the water was waist high at best, there was a marked difference in the cooler water temperature along the river floor. Standing up and feeling refreshed and comfortably cooIed, I  surveyed the sight of the river banks, the pastoral fields and woods all set against the rise of hills. The words of Hudson, perhaps sum up the experience best; "From Exford to Dulverton it runs (the river), singing aloud, foam-flecked, between high hills clothed to their summits in oak woods; after its union with the Barle it enters Devonshire as a majestic stream and flows calmly through rich green country; its wild romantic charm has been left behind"(37). My interest was drawn to the arching curve in the currents of the rivers as they fused together. I made my way towards this curve lying in the shallows of the v-shaped delta and spread myself across its borders as if to be in two rivers at one time.</p>
                <Segment vertical>
                    <Grid divided="vertically">
                        <Grid.Row columns={2}>
                            <Grid.Column>
                                <Image src={Media.img43} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img44} fluid rounded />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
                <Header as="h1">Black Pool.</Header>
                <Image src={Media.img45} fluid rounded />
                <br />
                <p>A little further down from the Meeting of the Waters was a bend in the river where it meets the steep rise of Whitestone Down. The river turns quite dramatically and is shaded by the presence of trees and tall cliff. The darker colour of the water does appear to lend its overall appearance to the aptly named <b>Black Pool</b> which marks the bend in the river. Here, we found two wooden fishermen’s huts, one each side of the river. The one closest to us, had a bench to the side with an interesting inscription, “Study to be quiet”. I looked up the quote later and discovered it was written by <b>Isaak Walton (1593-1663)</b>, a contemplation of his passion for Angling. The words were rather splendid I thought and for a short time, I sat on the bench and admired the view. I could sit here and be quiet, even if interrupted by the occasional noise of a car running along the road on the upper side of the hill. There was and often is, a rather soothing, hypnotic quality to the sound of running water. Perhaps, it was the similar allure of The River Meece, in Swallowford (what a lovely image that conjures up), in Staffordshire, that drew Walton to his love of Angling. He must have been kept pretty busy with small-holding, comprising a farmhouse, separate cottage, gardens and nine field. Most importantly, I suspect, was the stretch of The River Meece, which ran alongside his estate. Along these river-banks, he was able to hone and contemplate his passion for angling and at the age of sixty he wrote a book about this. "The Compleat Angler “(1653) draws on poetry and discussion with like-minded friends in a celebration of the outdoor pursuit, best summed up in his words;</p>
                <p className="quote">"I could sit quietly looking at the water, see some fishes disport themselves in silver streams, others leaping at the flies in several shapes and colours. Looking at the hills, I could behold them, spotted with woods and groves; looking down on the meadows". </p>
                <p>I do not know if Walton was inclined to take a dip in the water. He makes no mention of this, but we certainly felt a compulsion to try the waters. Once again, this was not so easy as the uneven sharp folds of the stony river bed took some negotiation. At least the water was deep enough here to swim freely and to dive down and peer into the gloom of the river bed. The current was also quite strong in places, but never in a manner that caused alarm. We were able to circle about and enjoy the full pleasure of being in the dark water, deep and unknown to us before now. We later agreed this had been one of the memorable swimming locations of the entire walk. Drying off by the bench, we saw what resembled a half-hidden track that seemed to offer a route along the river-bank. It meant, we did not have to walk along the road above, something neither of us were keen to do. We had to pick our way carefully along the small slither of bank between the river and the steep side of the cliff. Sometimes, the opportune support of a branch or stem of ivy dangling down from the trees, offered the difference between slipping or standing. On reaching firmer land, we were able to renew our step and passing a weir, found a footpath that took us through a small industrial estate. There was a slightly odd feeling as we walked past some of the workshops where the occupants cast an inquisitive look in our direction. It felt a little like we shouldn’t have been there or maybe we should have been at work.</p>
                <Segment vertical>
                    <Grid divided="vertically">
                        <Grid.Row columns={2}>
                            <Grid.Column>
                                <Image src={Media.img46} fluid rounded />
                            </Grid.Column>
                            <Grid.Column>
                                <Image src={Media.img47} fluid rounded />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
                <Header as="h1">The Exe Valley Railway.</Header>
                <Image src={Media.img48} fluid rounded />
                <br />
                <p>As we left the industrial estate, we walked under a former truss bridge that trains and carriages travelled along to Dulverton Station (Brushford) from Morebath Junction. The junction connected up the former Exe Valley Railway with the North Devon and Somerset routes. This line has long been broken up but there remains much of its imprint along the Exe Valley as we were to discover. This was the first relic we encountered. To my knowledge, it has never been possible to catch any train that would have taken you close to the full extent of The River Exe, but <b>The Exe Valley Railway (1884-1963)</b> certainly provided a good way to see a considerable stretch of it. Today, you can still catch a train from either Exmouth or Dawlish Warren at the mouth of The Exe Estuary and travel up to St. David’s Station in Exeter. Both sides offer fine views of the sea and estuary but the Dawlish line provides the added visual feast of the canal and river. However, the lines beyond St David’s only offer a fleeting view of the upstream Exe as the lines branch off in the direction of Barnstaple on The Tarka Line, or towards Bristol, leaving the Exe valley altogether at Rewe. However, up until October 1963, it was possible to travel catch “the Exe Valley flyer- a fussing saddle tank engine pulling two tiny carriages in the brown and cream livery of the old Great Western” (33) from St David’s Station and travel up to Morebath, a journey of just over 19 miles. Leaving St. David’s Station, the train would travel the 5-miles to Stoke Canon and then branch off in the direction of Tiverton and all within sight of the River Exe for much of the way. From Tiverton, the train would travel through wooded valleys and make stops at Bolham, Cove and Bampton, before finally arriving at its terminal at Morebath. If you had wished to travel on to Barnstaple or Taunton there was the connection from Dulverton Station. For seventy-nine years, the line offered a valuable commercial and passenger service to the various hamlets, villages and towns spread across large swathes of the Exe Valley.</p>
                <p>One person, who didn’t like the intrusion of the line on the valley, was the Writer <b>John Lloyd Warden Page (1858-1916)</b>. He wrote a number of accounts of his wanderings around Dartmoor and the rivers of Devon. The discovery of his book, The Rivers of Devon from source to sea with some account of the towns and villages on their banks (1893), has been particularly interesting. It is also freely available on The Internet Archive. His description of the areas, Charles and I covered during the walk, provides a lovely earlier reference point. For example, he described the source of the Exe in the “boggy realm of the Boggy King” as “about the most lonely and desolate spot on the moorland, abominable going at any time, but after heavy rain, simply impassable”. Of Exford, he wrote, “a healthy well-to-do village and that is about all that can be said of that”. The railway had only been running for a few years, before Page passed this way and it didn’t agree with him. “The repose of this valley has been broken by the locomotive”, he wrote, adding “where he gets his iron foot romance dies”. Page felt that the line spoilt some of the best views of the valley and “causes the worst echoes of the place”, but he also felt that it separated people from the river, because they could choose to “loll in the train and take in the scenery, but he will not see the half of it”. Instead, he chose to stay with the road, “a beautiful one, we stick to it as long as possible”. Today, he might well have more cause to complain about the motor car, but, for those able to walk as close to the river, as we did, you certainly are afforded the other half of it.  </p>
                <Image src={Media.img49} fluid rounded />
                <Header as="h1">Exebridge.</Header>
                <p className="quote">“And the highwayman came riding- Riding-riding- the highwayman came riding, up to the old inn-door. </p>
                <p className="quote-credit">Alfred Noyes. The Highwayman.</p>
                <p>The footpath continued the short distance towards our destination of <b>Exebridge</b>. Here the valley opened up with water meadows and the sight of Surridge Knap in the distance.  A few dog walkers were about and as we neared the bridge a couple of anglers stood knee high in the water casting their lines every now and then. The name of the village takes its name from the bridges that have stood here for centuries. The current stone bridge dates from the 18c, but the previous one was built of timber and positioned on stone piers. In 1649, it was found to be in a bad state of repair and dangerous for travellers to pass over and twenty years later “so ruinous no-one could travel over it” and it took several more decades before the current one was built (19). Part of the intractability of getting the bridge repaired may owe something to the fact that the bridge straddles the boundary of Devon and Somerset. To stand in the middle of the bridge is to be stood between two counties. And whilst there may have been a reluctance to shell out cash for repairs to what amounts to a shared bridge, this hasn’t prevented disputes over boundaries. Where enlargement or encroachment on boundaries has been an issue, such as the battle of the counties in 1894, the two counties have battled it out in Parliament. Somerset on that occasion, prevailed but looking down to the natural erosion of the riverbanks; Somerset is losing ground to Devon. </p>
                <p><b>The Anchor pub</b> may sound like an odd name for an inland pub. The need for an anchor might seem a little ambitious, except perhaps in flood. That is until, I discovered the wider interpretation of the word, Anchor, taken to mean stability and hope. Faggus may have found this in short supply at the time, he fatally stepped into the pub. He was the subject of another plot to capture him, only this time he was befriended by one of the assailants who plied him with alcohol. At a given moment and signal, he was set about and in the ensuing struggle, Faggus called for his horse, Winnie. Alerted by his call, she broke down the door with her hooves and upon entering the crowded pub, trampled down two assailants, before being shot. Faggus was tied up and taken for trial in Taunton and was hanged in 1671. For a happier ending, dig out a copy of Lorna Doone, where following a Royal Pardon he went on to live "with a good wife and a wonderful horse and all the country attached to him and he kept the law at a wholesome distance (sic) and thereafter the good and respectable Tom lived a godly and righteous (though not always) sober life; and brought up his children to honesty as the first of all qualifications". </p>
                <p>Leaving the village, on the return to Exeter, took us past the Exebridge Toll-house, which marked the southerly approach to the former Minehead toll road. Of octagonal shape, compact and sentinel, it seems precariously positioned between tangles of major roads. It’s somewhere you notice, rather than stop, as you’re too busy trying to remember which turning to take. I rather admired the bench to the side of the house. It showed a fatalistic, Devil may care Spirit, in the face of damage to the small little building over the years (46).    </p>
                <Divider />
                <List>
                    <List.Item as="h5">(10) Devon. D.St. Leger-Gordon (1963)</List.Item>
                    <List.Item as="h5">(19) The Ancient Bridges of the South of England. E. Jervoise (1930)</List.Item>
                    <List.Item as="h5">(33) Down along the Exe. J.M. Slader (1966)</List.Item>
                    <List.Item as="h5">(37) Afoot in Britain. W.H. Hudson (1909)</List.Item>
                    <List.Item as="h5">(41) bromptonregis.com/2018/03/18/st-nicholaass-priory</List.Item>
                    <List.Item as="h5">(42) bromptonregis.com/2018/03/04/baronsdown</List.Item>
                    <List.Item as="h5">(43) The King’s England. Somerset. Arthur Mee. (1940)</List.Item>
                    <List.Item as="h5">(44) Historical Report. Pixton Park. Heike Bernhardt M.A (2005)</List.Item>
                    <List.Item as="h5">(45) More Devon Byways. Annan Dickson (1952).</List.Item>
                    <List.Item as="h5">(46) The Toll-houses of North Devon. T. Jenkinson &mp; P. Taylor (2010)</List.Item>
                </List>
                <br />
                <br />
            </div>
            }></Chapter>
        );
    }
}

export default ChapterSeven;